#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=small_test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=00:10:00
#SBATCH --output=logs/slurm/output_%A.out

#SBATCH --ear=on
#SBATCH --ear-policy=monitoring
#SBATCH --ear-verbose=1

set -euo pipefail

module purge
module load 2025
module load Anaconda3/2025.06-1

cd $HOME/fact-ai/FairDICE

source activate fairdice

export MUJOCO_PY_MUJOCO_PATH="$HOME/.mujoco/mujoco210"
export MUJOCO_GL=egl
export D4RL_SUPPRESS_IMPORT_ERROR=1
export LD_LIBRARY_PATH="/usr/lib/nvidia:/usr/lib64/nvidia:$MUJOCO_PY_MUJOCO_PATH/bin:$CONDA_PREFIX/lib:${LD_LIBRARY_PATH:-}"

export CODECARBON_COUNTRY=Netherlands
export CODECARBON_REGION=Netherlands

python run_with_cc.py \
    --learner FairDICE \
    --divergence SOFT_CHI \
    --env_name MO-Hopper-v2 \
    --quality expert \
    --beta 1 \
    --seed 1 \
    --preference_dist uniform \
    --eval_episodes 2 \
    --batch_size 128 \
    --hidden_dim 768 \
    --num_layers 3 \
    --total_train_steps 10000 \
    --log_interval 1000 \
    --normalize_reward True \

python run_with_cc.py \
    --learner FairDICE \
    --divergence SOFT_CHI \
    --env_name MO-Hopper-v2 \
    --quality expert \
    --beta 1 \
    --seed 2 \
    --preference_dist uniform \
    --eval_episodes 2 \
    --batch_size 128 \
    --hidden_dim 768 \
    --num_layers 3 \
    --total_train_steps 10000 \
    --log_interval 1000 \
    --normalize_reward True \